name: Run flake8 & pytest

on:
  push:

jobs:
  CI:
    name: Flake8 & Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run flake8
        run: |
          pip install -r requirements.txt
          flake8 .

      # - name: Run Pytest
      #   run: |
      #     touch .env
      #     echo WRONG_IPS=123\n >> .env
      #     echo SERVER_IPS=${{ secrets.SERVER_IPS }} >> .env
      #     pytest -s
